"""Initial schema

Revision ID: 8cc43f8731ad
Revises: 
Create Date: 2026-01-29 20:37:01.408814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8cc43f8731ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # op.create_index('idx_regions_geometry', 'regions', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # op.create_index('idx_provinces_geometry', 'provinces', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_provinces_id'), 'provinces', ['id'], unique=False)
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_sqkm', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('postal_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # op.create_index('idx_municipalities_centroid', 'municipalities', ['centroid'], unique=False, postgresql_using='gist')
    # op.create_index('idx_municipalities_geometry', 'municipalities', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_municipalities_id'), 'municipalities', ['id'], unique=False)
    op.create_table('climate_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=True),
    sa.Column('target_year', sa.Integer(), nullable=True),
    sa.Column('avg_temp_change', sa.Float(), nullable=True),
    sa.Column('max_temp_change', sa.Float(), nullable=True),
    sa.Column('heatwave_days_increase', sa.Integer(), nullable=True),
    sa.Column('avg_precipitation_change', sa.Float(), nullable=True),
    sa.Column('extreme_rainfall_increase', sa.Float(), nullable=True),
    sa.Column('drought_risk_increase', sa.Float(), nullable=True),
    sa.Column('sea_level_rise_cm', sa.Float(), nullable=True),
    sa.Column('flood_risk_multiplier', sa.Float(), nullable=True),
    sa.Column('projection_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_projections_id'), 'climate_projections', ['id'], unique=False)
    op.create_table('crime_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_crimes_per_1000', sa.Float(), nullable=True),
    sa.Column('violent_crimes_per_1000', sa.Float(), nullable=True),
    sa.Column('property_crimes_per_1000', sa.Float(), nullable=True),
    sa.Column('crime_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crime_statistics_id'), 'crime_statistics', ['id'], unique=False)
    op.create_table('demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=True),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('population_density', sa.Float(), nullable=True),
    sa.Column('male_population', sa.Integer(), nullable=True),
    sa.Column('female_population', sa.Integer(), nullable=True),
    sa.Column('age_0_14', sa.Integer(), nullable=True),
    sa.Column('age_15_64', sa.Integer(), nullable=True),
    sa.Column('age_65_plus', sa.Integer(), nullable=True),
    sa.Column('median_age', sa.Float(), nullable=True),
    sa.Column('total_households', sa.Integer(), nullable=True),
    sa.Column('avg_household_size', sa.Float(), nullable=True),
    sa.Column('avg_income_euro', sa.Float(), nullable=True),
    sa.Column('unemployment_rate', sa.Float(), nullable=True),
    sa.Column('immigration_rate', sa.Float(), nullable=True),
    sa.Column('emigration_rate', sa.Float(), nullable=True),
    sa.Column('higher_education_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographics_id'), 'demographics', ['id'], unique=False)
    op.create_table('flood_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('high_hazard_area_pct', sa.Float(), nullable=True),
    sa.Column('medium_hazard_area_pct', sa.Float(), nullable=True),
    sa.Column('low_hazard_area_pct', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('population_exposed', sa.Integer(), nullable=True),
    sa.Column('buildings_exposed', sa.Integer(), nullable=True),
    sa.Column('flood_types', sa.JSON(), nullable=True),
    sa.Column('risk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flood_risk_id'), 'flood_risk', ['id'], unique=False)
    op.create_table('landslide_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('high_hazard_area_pct', sa.Float(), nullable=True),
    sa.Column('medium_hazard_area_pct', sa.Float(), nullable=True),
    sa.Column('low_hazard_area_pct', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('population_exposed', sa.Integer(), nullable=True),
    sa.Column('landslide_count', sa.Integer(), nullable=True),
    sa.Column('risk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landslide_risk_id'), 'landslide_risk', ['id'], unique=False)
    op.create_table('omi_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_code', sa.String(length=20), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=200), nullable=True),
    sa.Column('zone_type', sa.String(length=50), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_code')
    )
    # op.create_index('idx_omi_zones_centroid', 'omi_zones', ['centroid'], unique=False, postgresql_using='gist')
    # op.create_index('idx_omi_zones_geometry', 'omi_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_omi_zones_id'), 'omi_zones', ['id'], unique=False)
    op.create_table('seismic_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.Column('seismic_zone', sa.Integer(), nullable=True),
    sa.Column('peak_ground_acceleration', sa.Float(), nullable=True),
    sa.Column('hazard_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('historical_earthquakes_count', sa.Integer(), nullable=True),
    sa.Column('max_historical_magnitude', sa.Float(), nullable=True),
    sa.Column('risk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seismic_risk_id'), 'seismic_risk', ['id'], unique=False)
    op.create_table('investment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('omi_zone_id', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('price_trend_score', sa.Float(), nullable=True),
    sa.Column('affordability_score', sa.Float(), nullable=True),
    sa.Column('rental_yield_score', sa.Float(), nullable=True),
    sa.Column('demographics_score', sa.Float(), nullable=True),
    sa.Column('crime_score', sa.Float(), nullable=True),
    sa.Column('seismic_risk_score', sa.Float(), nullable=True),
    sa.Column('flood_risk_score', sa.Float(), nullable=True),
    sa.Column('landslide_risk_score', sa.Float(), nullable=True),
    sa.Column('climate_risk_score', sa.Float(), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=True),
    sa.Column('score_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['omi_zone_id'], ['omi_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_scores_id'), 'investment_scores', ['id'], unique=False)
    op.create_table('property_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('omi_zone_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('property_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'AGRICULTURAL', name='propertytype'), nullable=False),
    sa.Column('transaction_type', sa.Enum('SALE', 'RENT', name='transactiontype'), nullable=False),
    sa.Column('property_state', sa.String(length=50), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('rental_yield', sa.Float(), nullable=True),
    sa.Column('price_change_yoy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['omi_zone_id'], ['omi_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_prices_id'), 'property_prices', ['id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_property_prices_id'), table_name='property_prices')
    op.drop_table('property_prices')
    op.drop_index(op.f('ix_investment_scores_id'), table_name='investment_scores')
    op.drop_table('investment_scores')
    op.drop_index(op.f('ix_seismic_risk_id'), table_name='seismic_risk')
    op.drop_table('seismic_risk')
    op.drop_index(op.f('ix_omi_zones_id'), table_name='omi_zones')
    op.drop_index('idx_omi_zones_geometry', table_name='omi_zones', postgresql_using='gist')
    op.drop_index('idx_omi_zones_centroid', table_name='omi_zones', postgresql_using='gist')
    op.drop_table('omi_zones')
    op.drop_index(op.f('ix_landslide_risk_id'), table_name='landslide_risk')
    op.drop_table('landslide_risk')
    op.drop_index(op.f('ix_flood_risk_id'), table_name='flood_risk')
    op.drop_table('flood_risk')
    op.drop_index(op.f('ix_demographics_id'), table_name='demographics')
    op.drop_table('demographics')
    op.drop_index(op.f('ix_crime_statistics_id'), table_name='crime_statistics')
    op.drop_table('crime_statistics')
    op.drop_index(op.f('ix_climate_projections_id'), table_name='climate_projections')
    op.drop_table('climate_projections')
    op.drop_index(op.f('ix_municipalities_id'), table_name='municipalities')
    op.drop_index('idx_municipalities_geometry', table_name='municipalities', postgresql_using='gist')
    op.drop_index('idx_municipalities_centroid', table_name='municipalities', postgresql_using='gist')
    op.drop_table('municipalities')
    op.drop_index(op.f('ix_provinces_id'), table_name='provinces')
    op.drop_index('idx_provinces_geometry', table_name='provinces', postgresql_using='gist')
    op.drop_table('provinces')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_index('idx_regions_geometry', table_name='regions', postgresql_using='gist')
    op.drop_table('regions')
    # ### end Alembic commands ###
